### ISSUE TITLE
wrong zipUrl in update.json

### ISSUE THREAD

**Issue by IzzySoft** [stylemessiah/MagiskHideDenyBackup#1]
```json
"zipUrl": "https://github.com/stylemessiah/MagiskHideDenyBackup/releases/download/1.1/MagiskHideDenyBackup.v.1.1.zip"
```

real file name: `MagiskHideDenyBackup.v1.1.zip` (no dot after the `v`). This makes downloads fail.

**Comment by stylemessiah** [comment]
As I don't use this function of the modules I will remove it, I must have
overlooked it when I took it off the alt repo. Will fix a bit later today

**Comment by IzzySoft** [comment]
Some updaters use this functionality to fetch the latest ZIPs, so it would be great if you could fix it instead of removing it :wink: Thanks!

**Comment by stylemessiah** [comment]
I know how it works - clearly, because it was once on the repo, I just
don't use it....

**Comment by stylemessiah** [comment]
thanks for bringing up my oversight (not removing incorrect update.json info since i pulled the modules off the magisk alt repo) to my attention. all modules corrected now. as i have retired my main module, the GPay SQlite one, which WAS being updated occaisonally, and since the others are pretty static, theres really no need to update.json files in my modules

**Comment by IzzySoft** [comment]
Ah, sorry to see you removed the `update.json` entirely. I was planning to set up a custom repo and have a daily updater checker based on that (so I don't have to check a load of modules manually). Without that file I then cannot add the module.

But thanks for taking care, at least no "broken updates" then :wink:

**Comment by stylemessiah** [comment]
Sadly without going into super depth on why i took my stuiff off the repo, they can be abused, there is a mob that abused others work by scraping the magisk repo...the current alt magisk repo has an agreement with the mob that did this to scrape their repo, and im not cool with that. they also now have control of the Fox Magisk Module Manager app, so for me this is not a sign of confidenc ein the current state of the magisk repo, or the way people access it. i havent made acent off my work in years, and im not into others making money out of work ive donated to the community

**Comment by IzzySoft** [comment]
Ouch – yes, that's an issue I understand. Scraping without consent is not a nice thing to do. Though in this case: Your module is using a F/LOSS license, so everyone is free to even copy the code and use it according to the terms of GPLv2 (which BTW I use as well for most of my code)?

So let me give some background, though it's currently neither public nor fully decided yet: I plan to establish a repo for Magisk modules only accepting F/LOSS ones. For maintenance, I was looking at [magisk-modules-repo-util](https://github.com/ya0211/magisk-modules-repo-util) (I'm already in contact with the author and exchanging ideas, Sanmer is actively working on that). It has a counter-part Android app called [MRepo](https://github.com/ya0211/MRepo) which I just adopted into [my F-Droid repo](https://apt.izzysoft.de/fdroid). On my server I have some "measures" in place to mostly prevent scraping (I run the second largest F-Droid repo, and the probably largest German EPUB library, so you can bet a lot of scrapers passing by – just the logs of my server blocking them is already quite a huge thing :see_no_evil:)

The FoxMMM app just grew into quite a size-monster with its latest updates (factor 3 with just 2 versions), which is another reason I'm looking into something light-weight. Plus to me it is important that software I use is libre – hence a repo ensuring that and pointing out the licenses clearly will make it easier.

> and im not into others making money out of work ive donated to the community

Where shall I sign? Full ack to that. And if bad goes worse (talking out of experience here) the users of those having sold your work turn to you to solve their problems, arguing they've paid for it but cannot reach the "cash desk". Thanks – but no, thanks. You can look at my history in the FOSS world, I won't "sell out" – that's against my principles and against my respect for the FOSS developers & community. And I guess if I could sum up the time I've spent supporting FOSS and getting just 50 bucks per hour, I could easily drop my day job and enjoy the Caribbean (or which ever nice place to choose for spending the rest of your live with Caipis & Co) :see_no_evil:

**Comment by stylemessiah** [comment]
Now that you mention F-Droid i of course recognise your name, it had been
nagging at me id seen it somewhere before!

So you dont need to explain any further :)

Id be happy to re-stablish the update.json if you plan to launch the repo,
let me know if and when you have it up and running and advertised

Sorry i didnt make the connection sooner!

**Comment by IzzySoft** [comment]
Sounds like it's rather a "when" than an "if", pending [this issue](https://github.com/ya0211/magisk-modules-repo-util/issues/1#issue-1523722567). Plus another update I think about contributing (not using Github to host my Magisk repo, but instead `rsync` to my own server). No ETA yet, but it's realistic to be in the Easter basket or earlier.

Placed an "important" mark on the notification in my mail to give you a ping when the "when" is clear. Thanks a lot!

**Comment by stylemessiah** [comment]
I look forward to seeing your progress!

**Comment by stylemessiah** [comment]
Please save and use my email for future comms: ***@***.***

Im also just going to hide some of your comments in the closed issue thread
to protect the privacy of your projects :)

**Comment by IzzySoft** [comment]
> Please save and use my email for future comms: ***@***.***

:rofl: Looks like Github sanitized it (also in the notification mail), so I'll have to come back here. Mine can be found in the imprint of my above mentioned website, or by just prefixing my nick here with an "izzy" + "@", and suffixing it by ".de" :wink:
